### ISSUE TITLE
Feature request: Sub-albums

### ISSUE THREAD

**Issue by mam** [LycheeOrg/Lychee-v3#186] opened 2019-02-04 10:41 UTC
It would be nice with the ability to create albums within albums, e.g. having The Great Wall, The Forbidden City under an album called China.

**Comment by d7415** [comment] 2019-02-04 11:46
Duplicate of #78. Feature will be released in v4. Available to test in [Lychee-Laravel](https://github.com/LycheeOrg/Lychee-Laravel)

**Closed as completed by d7415** 2019-02-04 11:46 UTC
Labels: Duplicate
