### ISSUE TITLE
Lychee cannot import or upload photos

### ISSUE THREAD

**Issue by Lumigenic** [LycheeOrg/Lychee-v3#190] opened 2019-02-11 08:32 UTC
Lychee Issue

### Detailed description of the problem
I've installed Lychee (using Softaculous software installer) on two different domains on my server (a VPS hosted by inMotionHosting.com). I cannot add photos at all. I have tried upload, and get “Server Returned an unknown response.” When I check the console as advised, I see a Server Status 500, see the attached screen shot. 

If I try to import from a link, I get "The import has been finished, but returned warnings or errors." The error_log shows

 2019-02-11 00:04:32 - error - Lychee\Modules\Import::url (64) 	- Photo type not supported (marcshargel.com/gallery/uploads/import/532P017.jpg)

 I tried renaming a file with the file extension “.jpeg” instead of “.jpg” and got the same result.

This made me think there was something wrong with my JPEG files. They were generated by Lightroom. I opened them and re-saved using Photoshop. Same result.  I tried a PNG file created by a screenshot. Same result. Here is what the error log said after that attempt.

00:00:01 - error - Lychee\Modules\Import::url (64) 	- Photo type not supported (marcshargel.com/gallery/uploads/import/Chicago%20Ice.png)

“Import from Server” produces similar results.

### Steps to reproduce the issue
Attempt to import or upload any photo file.

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics ----------- 
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details. 
Warning: You may experience problems with the Dropbox- and URL-Import. Edit your php.ini and set allow_url_fopen to 1. 
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that. 
No critical problems found. Lychee should work without problems!   

System Information ------------------ 
Lychee Version:  3.1.6 
DB Version:      030102 
System:          Linux 
PHP Version:     5.6 
MySQL Version:   50641 
Imagick:         - 
Imagick Active:  1 
Imagick Version: - GD 
Version:      bundled (2.1.0 compatible) 
Plugins:         

WHOA! 
allow_url_fopen *IS* set to 1 as you can see at 
http://marcshargel.com/gallery/phpinfo.php

And I don’t understand why IMAGICK is unavailable. Does Lychee not install it along with the Lychee code itself?

You can check my PHP setup here:
http://marcshargel.com/gallery/phpinfo.php

### Browser and system
I'm running on MacOS 10.11.6, I get the same results in Safari (11.1.2) and Firefox (latest version) and Chrome 41. 
Check my php setup at http://marcshargel.com/gallery/phpinfo.php
The server is running PHP 5.6 and I have increased 

upload_max_filesize = 256M
upload_max_size = 512M

 as suggested in the FAQ. I also increased 
memory_limit = 128M

If you would like to try the above yourself, email me privately at webmaster(at)lumigenic(dot)com
And I will reset my login temporarily and share them with you so you can examine the behavior on my server directly.

THANK YOU IN ADVANCE for any time you devote to helping me resolve this problem.

Marc in California

 
![screen shot 2019-02-10 at 11 49 28 pm](https://user-images.githubusercontent.com/47445268/52552169-245d1300-2d94-11e9-9144-c261ee84b1e1.png)
![screen shot 2019-02-10 at 11 54 56 pm](https://user-images.githubusercontent.com/47445268/52552181-2b842100-2d94-11e9-9f3e-e9685d8b4e8b.png)

**Comment by Lumigenic** [comment] 2019-02-11 08:42
BTW, I called this "*Lychee* cannot import or upload Photos." I have no doubt that since this behavior seems to be peculiar to my installed instance, the cause must be something particular to my installation or my server. But as far as I can tell everything is in order. PLEASE contradict that! I'd really like to get Lychee running, and I'd think someone else would create the same snag sometime. So if you can give me hint as to what might have gone haywire on my installation/server, I'd be grateful.

**Comment by ildyria** [comment] 2019-02-11 09:58
```
PHP Version 5.6.40
```
Can you update to Php 7.2 ? 
https://github.com/LycheeOrg/Lychee/commit/0607e9b5d96a73d16a71b0f4d5123eb7f71f5e8d

Also...
```
Lychee Version: 3.1.6
DB Version: 030102
```

The current version is 3.2.11: https://github.com/LycheeOrg/Lychee/releases/tag/v3.2.11

**Comment by ildyria** [comment] 2019-02-11 11:37
> And I don’t understand why IMAGICK is unavailable. Does Lychee not install it along with the Lychee code itself?

Nope, you need to install it yourself with something like:
```
apt install imagick
apt install php-imagick
```

**Comment by ildyria** [comment] 2019-02-12 15:05
Any update ?

**Comment by Lumigenic** [comment] 2019-02-13 06:35
ildyria: THANK YOU for the quick response! 
As you suggested, I have switched PHP version to 7.2. I confirmed that it is active, checking 
http://marcshargel.com/gallery/phpinfo.php

Following your link (thanks) I downloaded the new V 3.2.11 Lychee files and uploaded them to
http://marcshargel.com/gallery/
overwriting the previous version. 

Returning to Lychee, I see a tremendous difference! Photos WILL upload. Photos WILL import. Strangely, neither process is 100% reliable. Both omit some images if I attempt a large batch. With upload there were only 3 missing from a batch of 103. I had to manually see which hadn’t made it into the album, and upload those individually. The progress does seem to be accurately reflected. There were a few images that never got the green “FINISHED” next to them, but most did. So I had pretty good feedback with uploading.

Import from server was less reliable, perhaps 20% of the images didn’t make it into the album. Oh, and with Import the black window with “Processing” in it never changed. I left it working all night: it just sat there. I reloaded the page to find most of my images had arrived. I wonder if the process had timed out. But with both Upload and Import, the missed images were scattered (as if randomly) throughout the list, so if the trouble was due to timeout, the images are being processed in an unpredictable order.

Neither Upload nor Import ever arrived at a notification of being finished nor said that I should click something to proceed. I waited what seemed long enough, then reloaded the page to see what had been accomplished.

I have not yet installed imagick, and while I thought Lychee was supposed to work without it, I could imagine things improving once I do. I’ll post another update after I do that installation. 

BTW, Softaculous software installation service/product seems not to be connected to the code you've made available through github. They are still offering 3.1.6 as "current" and seem not to be aware of anything since that. That is how I came to install that antiquated version just a few days ago.

I want to express my great gratitude to you for your advice on my installation efforts. With your help I have Lychee in a usable condition. I’m hoping to iron out the relatively small bugs that remain for me. But I have posted four albums via Lychee, working around the inconveniences. I only wish the support people at companies to whom I pay money for commercial software were so concerned and attentive as you. Thank you.

**Comment by Lumigenic** [comment] 2019-02-13 06:52
Addendum: I've found what I'd think is a minor bug, except I cannot imagine I'd have been the first to run into it. Changing Album Sorting does not work. No matter which menu choice I apply, I see this: 
![screen shot 2019-02-12 at 10 50 19 pm](https://user-images.githubusercontent.com/47445268/52692452-cd347b00-2f18-11e9-93a2-64f854652ca9.png)

**Comment by d7415** [comment] 2019-02-13 10:03
> I wonder if the process had timed out. 

If you're uploading a lot of photos you may want to try [this](https://github.com/LycheeOrg/Lychee/wiki/FAQ#im-importing-a-lot-of-photos-using-import-from-server-and-lychee-times-out-before-its-done).

> BTW, Softaculous software installation service/product seems not to be connected to the code you've made available through github. 

This is the first I've heard of Softaculous. As far as I am aware we're not associated with them, so it's up to them to watch for releases. Github makes it really easy.

**Comment by ildyria** [comment] 2019-02-13 10:28
@Lumigenic
- **about the small bug (change sorting), can you open a new issue ?** :+1: 
- about the import from server option, there is already an issue opened on that.
- about the upload of a lot of pictures, I think one of the problem is that may php process multiple pictures at the same time and I fear that sometimes it runs out of memory or something like that. :(

I'm closing this issue as your main problem is solved. Feel free to open new ones for the next problems you have

**Closed as completed by ildyria** 2019-02-13 10:28 UTC
Labels: Not an Issue

**Comment by Lumigenic** [comment] 2019-02-13 21:36
OK, will do. Closing this issue seems appropriate, the Lychee and PHP version updates did fix the main problem. 

Softaculous is a commercial service; I paid them for access to many many bits of server side software. They make installation fast and easy, flagging needed server updates, for example, in the course of installation. I was suggesting you contact them. They appear to be under the mis-impression that Electerious is the current developer/publisher of Lychee, so are distributing out of date versions to people like me. 

I will open another issue about Album Sorting.

I want to underscore my great gratitude to you for your attentive help and fast, direct communication.  I only wish the support people at companies to whom I pay money for commercial software were so concerned and attentive as you. Thank you.

**Comment by Lumigenic** [comment] 2019-02-16 07:24
Benoît,

I began writing up the change sorting bug as a new issue. I tried it with Firefox, and it works fine. I re-tested with Safari, where it failed originally, and it work fine. So I cannot reproduce the problem. 

I’m dropping it, so no new issue. 

Thanks for all the work you’ve done to make Lychee available for people like me to use and enjoy!

Marc Shargel
