### ISSUE TITLE
Can't download picture or album in Google Chrome

### ISSUE THREAD

**Issue by lilkayden** [LycheeOrg/Lychee-v3#155] opened 2018-12-24 17:38 UTC
### Detailed description of the problem
When trying to download a picture or album using the download button in google chrome, chrome gives "Failed - Network Error" 
Console shows - main.js:14 Resource interpreted as Document but transferred with MIME type application/octet-stream:

Only the download button doesn't work. Users are still able to download if they right click and save as or go in full photo and save as. 

### Steps to reproduce the issue
Upload a photo, and click on the download button for the photo in google chrome. 

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50560
Imagick:         1
Imagick Active:  1
Imagick Version: 1656
GD Version:      bundled (2.1.0 compatible)
Plugins:         

### Browser and system
Google Chrome - Version 71.0.3578.98 (Official Build) (64-bit)
Windows 10 Pro Version 1809 Build 17763.195

**Comment by bennettscience** [comment] 2018-12-26 01:35
That's an old version of Lychee. I can't get it to reproduce using 3.2.7.

**Comment by lilkayden** [comment] 2018-12-26 04:09
> That's an old version of Lychee. I can't get it to reproduce using 3.2.7.

I didn't know there was another version so I updated my version from the git to version 3.2.8. However I'm still experiencing the same problem.  

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.8
DB Version:             update_030208
System:                 Linux
PHP Version:            5.6
MySQL Version:          50560
Imagick:                1
Imagick Active:         1
Imagick Version:        1656
GD Version:             bundled (2.1.0 compatible)
Plugins:   

Test steps:
I updated my production and reinstalled on my dev domain. Same thing happens on both.
When I click the download button I get:
Resource interpreted as Document but transferred with MIME type application/zip: when I try downloading the whole album and
Resource interpreted as Document but transferred with MIME type application/octet-stream: when I try downloading a single image. 

This is using incognito mode in google chrome Version 71.0.3578.98 (Official Build) (64-bit).

**Comment by lilkayden** [comment] 2018-12-26 05:44
Here is from clicking on download from a photo
![image](https://user-images.githubusercontent.com/46110593/50433571-0cdecf00-08a7-11e9-91c7-82db0ab633ed.png)

Here is from downloading a album
![image](https://user-images.githubusercontent.com/46110593/50433609-4283b800-08a7-11e9-85fe-21b8ef720c83.png)

![image](https://user-images.githubusercontent.com/46110593/50433623-58917880-08a7-11e9-90a4-d3f8428cff49.png)

**Comment by bennettscience** [comment] 2018-12-29 02:32
I still can't reproduce, but I'm not using PHP < 7 any more. There could also be a Chrome extension affecting the javascript on the page. Can you disable some and try again to narrow that problem down?

**Comment by lilkayden** [comment] 2018-12-29 04:37
> I still can't reproduce, but I'm not using PHP < 7 any more. There could also be a Chrome extension affecting the javascript on the page. Can you disable some and try again to narrow that problem down?

I've tried in incognito mode, same thing. I've had a few users report the same thing so I want to say it's something with chrome. However I will try it with php 7 on my test server to see if it makes any difference.

**Comment by lilkayden** [comment] 2018-12-29 06:08
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.8
DB Version:             update_030208
System:                 Linux
PHP Version:            7
MySQL Version:          50560
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             2.2.5
Plugins:                

same thing with php 7

Anyone else have a Lychee instance I can check?

**Comment by ildyria** [comment] 2018-12-29 08:18
@lilkayden Can you try to download this album: ...
Do not bother trying to download a picture, it is not implemented yet.

**Comment by lilkayden** [comment] 2018-12-29 18:17
> @lilkayden Can you try to download this album: ...
> Do not bother trying to download a picture, it is not implemented yet.

It still gave the same error in console but your download did complete successfully. 
I see this is different than on mines.

Yours works
![image](https://user-images.githubusercontent.com/46110593/50541077-0339bd80-0b6c-11e9-9f8a-1b346338d13d.png)

Mines fails
![image](https://user-images.githubusercontent.com/46110593/50541082-0cc32580-0b6c-11e9-93b4-f05993dc8a77.png)

**Comment by ildyria** [comment] 2018-12-29 19:02
Yes. I'm using the next version.
From that, what may be the reason of the crash is the zipping process. Verify that php-zip is installed. 😶

**Comment by lilkayden** [comment] 2018-12-29 19:42
> Yes. I'm using the next version. From that, what may be the reason of the crash is the zipping process. Verify that php-zip is installed. 😶 
> > @lilkayden Can you try to download this album: ... > Do not bother trying to download a picture, it is not implemented yet. It still gave the same error in console but your download did complete successfully. I see this is different than on mines. Yours works ![image](https://user-images.githubusercontent.com/46110593/50541077-0339bd80-0b6c-11e9-9f8a-1b346338d13d.png) Mines fails ![image](https://user-images.githubusercontent.com/46110593/50541082-0cc32580-0b6c-11e9-93b4-f05993dc8a77.png) 

Indeed, Zip is installed:
![image](https://user-images.githubusercontent.com/46110593/50541619-9b896f80-0b77-11e9-889f-bf9c004d90ad.png)

The problem is:
![image](https://user-images.githubusercontent.com/46110593/50541631-c2e03c80-0b77-11e9-8ed7-061a3a59aa2c.png)

It zips and downloads, but then it can't complete the download. It hits 100% and then it doesn't save. Where as when I download yours it hits 100% and completes.

**Comment by ildyria** [comment] 2018-12-29 21:52
I'm sorry but on that one, I don't have any idea.
It seems related to this issue: https://github.com/LycheeOrg/Lychee/issues/17
(but closed because solved in the next big version).

**Comment by lilkayden** [comment] 2018-12-29 21:59
Ya it looks like the next big version should fix this issue. Any ETA on that version?

**Comment by ildyria** [comment] 2018-12-29 22:00
It is actually already working and available: https://github.com/LycheeOrg/Lychee-Laravel
It is just not documented on how to install easily it.

**Comment by SabrinaFinkel** [comment] 2018-12-30 11:50
@lilkayden, can you please post your php.ini here? Maybe you have a download/upload limit that is too small? 🤔

Do you get the same error using Microsoft Edge and [Mozilla Firefox](https://www.mozilla.org/)?

**Comment by lilkayden** [comment] 2018-12-30 18:43
> @lilkayden, can you please post your php.ini here? Maybe you have a download/upload limit that is too small? 🤔
> 
> Do you get the same error using Microsoft Edge and [Mozilla Firefox](https://www.mozilla.org/)?

Since I upgraded to 3.2.8 we are not having issues with Microsoft Edge, IE or Mozilla Firefox. Just Google Chrome. 

Attached is my php.ini
[php.ini.txt](https://github.com/LycheeOrg/Lychee/files/2717411/php.ini.txt)

**Comment by SabrinaFinkel** [comment] 2018-12-31 17:46
The php.ini looks fine. 🤔
I do not have any other ideas for now. 😅

**Comment by ildyria** [comment] 2019-02-19 23:22
Any updates? Or I'm closing this in 24 hours.

**Closed as completed** 2019-03-07 21:14 UTC
Labels: bug
